- name: configure webserver with nginx
  hosts: webserver
  sudo: True
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/site-available/default
  
    - name: enable configure
      file: >
         dest=/etc/nginx/site-available/default
         src=/etc/nginx/site-available/default
         state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      systemctl: name=nginx state=restarted
