---
- name: configure webserver with nginx and tls
  hosts: webservers
  sudo: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/nginx.conf
    dir_file: /Users/zhangduan/Documents/ansible_nginx/playbooks/
    server_name: localhost

  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes
      
    - name: create dir for tls cert
      file: path=/etc/nginx/ssl state=directory

    - name: copy tls key
      copy: src={{dir_file}}files/nginx.key dest={{key_file}} owner=root mode=0600
      notify: restart nginx

    - name: copy tls cert
      copy: src={{dir_file}}files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy tls config
      copy: src={{dir_file}}templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configure
      copy: src={{dir_file}}files/nginx.conf dest={{conf_file}}
      notify: restart nginx


    - name: copy index.html
      template: src={{dir_file}}templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
    
    - name: start nginx
      systemd: name=nginx state=started


  handlers:
  - name: restart nginx
    systemd: name=nginx state=restarted



