- name: configure webserver with nginx and tls
  hosts: webservers
  sudo: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:
    - name: install nginx
      yum: name=nginx cache_update=yes cache_valid_time=3600
      
    - name: create dir for tls cert
      file: path=/etc/nginx/ssl state=directory

    - name: copy tls key
      copy: src=/file/nginx.key dest={{key_file}} owner=root mode=0600
      notify: restart nginx

    - name: copy tls cert
      copy: src=/file/nginx/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy tls config
      copy: src=/templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configure
      file: src=/etc/nginx/sites-enabled/default src={{conf_file}} state=link
      notify: restart nginx


    - name: copy index.html
      template: src=teplates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    handlers:
      - name: restart nginx
        systemd: name=nginx state=restarted



